### ISSUE TITLE
FileNotFoundError while running ltlcross

### ISSUE THREAD

**Issue by adl** [xblahoud/seminator-evaluation#2]
This was reported by one reviewer

> When using more than one process running segment [3] of
> `complement/Run_ltlcross.ipynb`, for some reason the names of the generated
> `lcw-*` files didn't always match what it expected, which resulted in
> `FileNotFoundErrors`, e.g.,
> ```
> "/usr/local/lib/python3.7/dist-packages/ltlcross_wrapper/modular.py"
> FileNotFoundError: [Errno 2] No such file or directory: 'other_tools/GOAL-20200107/lcw-51-boot_cmd.properties
> ```
> It seems that some files are deleted out of order (and thus don't exist
> anymore when they are accessed).
> Running it with only one process worked as expected.

I have not been able to reproduce that.  I tried the default `processes=4` argument as well as `processes=3`.

Fanda told me that the files are deleted only once they have been processed, so they should not disappear.  Reading the report again I wonder if this reviewer really updated the `process` argument as we expected, or if they somehow managed to execute the cell's code multiple times in different kernels running in parallel.

**Comment by adl** [comment]
So the only way I have found to execute the cell twice in parallel is to duplicate the notebook, and start cell `[3]` in each of those. I'd consider very unlikely that the reviewer did that.   As the numbers in lcw-* are PID numbers, even this scenario seemed to work fine, at least initially.  Both notebooks were happily running when I went to bed, but when I woke up this morning, one of them had aborted with:
```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.7/dist-packages/ltlcross_wrapper/modular.py", line 317, in _clean_goal
    os.remove(f"{self.goal_root}/{pref}-boot_cmd.properties")
FileNotFoundError: [Errno 2] No such file or directory: 'other_tools/GOAL-20200107/lcw-97639-boot_cmd.properties'
"""

The above exception was the direct cause of the following exception:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-ea86b7e48e0d> in <module>
      6                       name=f"{name}",
      7                       processes=4)
----> 8     m.run()
      9 
     10 for name in names:

/usr/local/lib/python3.7/dist-packages/ltlcross_wrapper/modular.py in run(self, **kwargs)
    325         Modulizer.run(self, pool=pool, **kwargs)
    326 
--> 327         pool.map(self._clean_goal, range(processes), chunksize=1)
    328 
    329 

/usr/lib/python3.7/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    266         in a list that is returned.
    267         '''
--> 268         return self._map_async(func, iterable, mapstar, chunksize).get()
    269 
    270     def starmap(self, func, iterable, chunksize=None):

/usr/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

FileNotFoundError: [Errno 2] No such file or directory: 'other_tools/GOAL-20200107/lcw-97639-boot_cmd.properties'
```
I should add that only cell `[3]` was executed, I did not ask for execution of cell `[4]`.

I'll try to restart only one notebook with `processes=8`, maybe this issue is triggered somehow when too much memory is used?

**Comment by adl** [comment]
I've used `processes=16` and a single notebook, and can reproduce the issue:

```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.7/dist-packages/ltlcross_wrapper/modular.py", line 317, in _clean_goal
    os.remove(f"{self.goal_root}/{pref}-boot_cmd.properties")
FileNotFoundError: [Errno 2] No such file or directory: 'other_tools/GOAL-20200107/lcw-34024-boot_cmd.properties'
"""

The above exception was the direct cause of the following exception:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-33f037d96a5f> in <module>
      6                       name=f"{name}",
      7                       processes=16)
----> 8     m.run()
      9 
     10 for name in names:

/usr/local/lib/python3.7/dist-packages/ltlcross_wrapper/modular.py in run(self, **kwargs)
    325         Modulizer.run(self, pool=pool, **kwargs)
    326 
--> 327         pool.map(self._clean_goal, range(processes), chunksize=1)
    328 
    329 

/usr/lib/python3.7/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    266         in a list that is returned.
    267         '''
--> 268         return self._map_async(func, iterable, mapstar, chunksize).get()
    269 
    270     def starmap(self, func, iterable, chunksize=None):

/usr/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

FileNotFoundError: [Errno 2] No such file or directory: 'other_tools/GOAL-20200107/lcw-34024-boot_cmd.properties'
```

At this point, the contents of the directories are as follows:
```
user@29d388bc97ea:~/src/seminator-evaluation/complement$ ls -l
total 10096
-rw-r--r-- 1 user user   59701 Jan 28 11:15 GOAL-variants.ipynb
-rw-r--r-- 1 user user  363951 Jan 28 11:15 Results_BA.ipynb
-rw-r--r-- 1 user user    9864 Mar 15 11:32 Run_ltlcross.ipynb
-rw-r--r-- 1 user user  330615 Jan 28 11:15 Seminator_variants.ipynb
drwxr-xr-x 2 user user    4096 Mar 15 11:00 __pycache__
drwxr-xr-x 2 user user    4096 Jan 28 11:15 data
drwxr-xr-x 2 user user    4096 Jan 28 11:15 data.goal_variants
drwxr-xr-x 2 user user    4096 Jan 28 11:15 data.seminator_variants
-rw-r--r-- 1 user user     386 Mar 15 11:30 lcw-34025.in.hoa
-rw-r--r-- 1 user user       0 Mar 15 11:26 lcw-34025.out.hoa
-rw-r--r-- 1 user user     512 Mar 15 11:10 lcw-38.in.hoa
-rw-r--r-- 1 user user       0 Mar 15 11:06 lcw-38.out.hoa
-rw-r--r-- 1 user user     591 Mar 15 11:13 lcw-40.in.hoa
-rw-r--r-- 1 user user     550 Mar 15 11:11 lcw-42.in.hoa
-rw-r--r-- 1 user user     567 Mar 15 11:11 lcw-51.in.hoa
-rw-r--r-- 1 user user 1996024 Mar 15 11:18 literature_det.csv
-rw-r--r-- 1 user user  921637 Mar 15 11:18 literature_det.log
drwxr-xr-x 2 user user   32768 Mar 15 11:18 literature_det.parts
-rw-r--r-- 1 user user      45 Mar 15 11:18 literature_det_bogus.ltl
-rw-r--r-- 1 user user 6233907 Mar 15 11:32 literature_sd.csv
-rw-r--r-- 1 user user  300584 Mar 15 11:32 literature_sd.log
drwxr-xr-x 2 user user   12288 Mar 15 11:32 literature_sd.parts
-rw-r--r-- 1 user user       0 Mar 15 11:32 literature_sd_bogus.ltl
drwxr-xr-x 1 user user    4096 Jan 28 11:18 other_tools
-rw-r--r-- 1 user user    2298 Jan 28 11:15 tools.py
-rw-r--r-- 1 user user    1640 Jan 28 11:15 tools_goal_variants.py
-rw-r--r-- 1 user user     782 Jan 28 11:15 tools_seminator_variants.py
user@29d388bc97ea:~/src/seminator-evaluation/complement$ cd other_tools/
user@29d388bc97ea:~/src/seminator-evaluation/complement/other_tools$ ls -l
total 8
drwxr-xr-x 1 user user 4096 Mar 15 11:32 GOAL-20200107
drwxr-xr-x 2 user user 4096 Jan 28 11:18 roll-library
user@29d388bc97ea:~/src/seminator-evaluation/complement/other_tools$ cd GOAL-20200107/
user@29d388bc97ea:~/src/seminator-evaluation/complement/other_tools/GOAL-20200107$ ls -la
total 216
drwxr-xr-x 1 user user  4096 Mar 15 11:32 .
drwxr-xr-x 1 user user  4096 Jan 28 11:18 ..
-rw-r--r-- 1 user user   822 Jan  7 15:42 boot.properties
-rw-r--r-- 1 user user   686 Jan  7 15:42 boot_cmd.properties
drwxr-xr-x 2 user user  4096 Jan  7 15:42 data
drwxr-xr-x 3 user user  4096 Jan  7 15:42 doc
-rwxr-xr-x 1 user user   774 Jan  7 15:42 gc
-rw-r--r-- 1 user user  1593 Jan  7 15:42 gc.bat
-rwxr-xr-x 1 user user   554 Jan  7 15:42 goal
-rw-r--r-- 1 user user  1759 Jan  7 15:42 goal.bat
-rw-r--r-- 1 user user 64144 Jan  7 15:42 goal.icns
-rw-r--r-- 1 user user   696 Mar 15 11:18 lcw-34022-boot_cmd.properties
-rwxr-xr-x 1 user user   785 Mar 15 11:18 lcw-34022-gc
drwxr-xr-x 2 user user  4096 Mar 15 11:22 lcw-34022-jpf-shadow
-rw-r--r-- 1 user user   696 Mar 15 11:18 lcw-34026-boot_cmd.properties
-rwxr-xr-x 1 user user   785 Mar 15 11:18 lcw-34026-gc
drwxr-xr-x 2 user user  4096 Mar 15 11:21 lcw-34026-jpf-shadow
-rw-r--r-- 1 user user   696 Mar 15 11:18 lcw-34028-boot_cmd.properties
-rwxr-xr-x 1 user user   785 Mar 15 11:18 lcw-34028-gc
drwxr-xr-x 2 user user  4096 Mar 15 11:21 lcw-34028-jpf-shadow
-rw-r--r-- 1 user user   696 Mar 15 11:18 lcw-34030-boot_cmd.properties
-rwxr-xr-x 1 user user   785 Mar 15 11:18 lcw-34030-gc
drwxr-xr-x 2 user user  4096 Mar 15 11:21 lcw-34030-jpf-shadow
-rw-r--r-- 1 user user   696 Mar 15 11:18 lcw-34036-boot_cmd.properties
-rwxr-xr-x 1 user user   785 Mar 15 11:18 lcw-34036-gc
drwxr-xr-x 2 user user  4096 Mar 15 11:21 lcw-34036-jpf-shadow
drwxr-xr-x 2 user user  4096 Jan  7 15:42 lib
-rw-r--r-- 1 user user   180 Jan  7 15:42 logging.properties
-rwxr-xr-x 1 user user   881 Jan  7 15:42 mklib
-rw-r--r-- 1 user user   796 Jan  7 15:42 mklib.bat
drwxr-xr-x 2 user user  4096 Jan 28 11:18 plugins
drwxr-xr-x 3 user user  4096 Jan  7 15:42 scripts
-rw-r--r-- 1 user user 20727 Jan  7 15:42 splash.png
user@29d388bc97ea:~/src/seminator-evaluation/complement/other_tools/GOAL-20200107$ 
```

**Comment by adl** [comment]
I've changed `ltlcross/modular.py` to add some print statements in `_prepare_goal()` and `_clean_goal()`.  Here is what I see (with `processes=20`):

```
prepare lcw-201
prepare lcw-204
prepare lcw-207
prepare lcw-210
prepare lcw-213
prepare lcw-216
prepare lcw-219
prepare lcw-222
prepare lcw-225
prepare lcw-228
prepare lcw-231
prepare lcw-234
prepare lcw-237
prepare lcw-240
prepare lcw-243
prepare lcw-246
prepare lcw-249
prepare lcw-252
prepare lcw-255
prepare lcw-258
clean lcw-255
clean lcw-234
clean lcw-243
clean lcw-207
clean lcw-222
clean lcw-237
clean lcw-237
clean lcw-210
clean lcw-252
clean lcw-204
clean lcw-231
clean lcw-246
clean lcw-249
clean lcw-240
clean lcw-219
clean lcw-213
clean lcw-225
clean lcw-258
clean lcw-216
clean lcw-228

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/user/.local/lib/python3.7/site-packages/ltlcross_wrapper/modular.py", line 319, in _clean_goal
    os.remove(f"{self.goal_root}/{pref}-boot_cmd.properties")
FileNotFoundError: [Errno 2] No such file or directory: 'other_tools/GOAL-20200107/lcw-237-boot_cmd.properties'
"""

The above exception was the direct cause of the following exception:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-124b6def865c> in <module>
      6                       name=f"{name}",
      7                       processes=20)
----> 8     m.run()
      9 
     10 for name in names:

~/.local/lib/python3.7/site-packages/ltlcross_wrapper/modular.py in run(self, **kwargs)
    327         Modulizer.run(self, pool=pool, **kwargs)
    328 
--> 329         pool.map(self._clean_goal, range(processes), chunksize=1)
    330 
    331 

/usr/lib/python3.7/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    266         in a list that is returned.
    267         '''
--> 268         return self._map_async(func, iterable, mapstar, chunksize).get()
    269 
    270     def starmap(self, func, iterable, chunksize=None):

/usr/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

FileNotFoundError: [Errno 2] No such file or directory: 'other_tools/GOAL-20200107/lcw-237-boot_cmd.properties'
```

You can see that clean 201 is missing, and that clean 237 is called twice.  

I suspect it has to do with the fact that [`pool.map(self._clean_goal, range(processes), chunksize=1)`](https://github.com/xblahoud/ltlcross_wrapper/blob/1c85b3a73d6a43d6367adb6a4ebdcc4fdcefbe76/ltlcross_wrapper/modular.py#L327) will correctly create `processes` tasks, but does not guarantee that each task will be handled by a different worker.  Maybe worker 237 finished its first task before worker 201 even had a chance to look at the queue of tasks, so in the end worker 237 handled two cleaning tasks.

**Comment by adl** [comment]
I'm currently experimenting with the following solution.  There seems to be a barely documented way to attach finalization functions to pool workers, using the `multiprocessing.util.Finalize` class. Those functions are called when the workers are killed with `pool.join()`.

```diff
user@518e74957387:~/src/ltlcross_wrapper$ git diff
diff --git a/ltlcross_wrapper/modular.py b/ltlcross_wrapper/modular.py
index 15f9a25..dca0aa8 100644
--- a/ltlcross_wrapper/modular.py
+++ b/ltlcross_wrapper/modular.py
@@ -230,6 +230,13 @@ def make_executable(file):
     os.chmod(file, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
 
 
+def _clean_goal(pref):
+    """Delete files created on process initialization"""
+    os.remove(f"{pref}-boot_cmd.properties")
+    os.remove(f"{pref}-gc")
+    shutil.rmtree(f"{pref}-jpf-shadow")
+
+
 class GoalModulizer(Modulizer):
     """Run in parallel ltlcross tasks with GOAL tool.
 
@@ -311,12 +318,7 @@ class GoalModulizer(Modulizer):
         print(mod_gc, file=open(gc_new, "w"))
         make_executable(gc_new)
 
-    def _clean_goal(self, i):
-        """Delete files created on process initialization"""
-        pref = self._get_LCW_TMP()
-        os.remove(f"{self.goal_root}/{pref}-boot_cmd.properties")
-        os.remove(f"{self.goal_root}/{pref}-gc")
-        shutil.rmtree(f"{self.goal_root}/{pref}-jpf-shadow")
+        multiprocessing.util.Finalize(None, _clean_goal, [f"{self.goal_root}/{pref}"], exitpriority=10)
 
     def run(self, **kwargs):
         processes = kwargs.get("processes",self.processes)
@@ -324,7 +326,8 @@ class GoalModulizer(Modulizer):
 
         Modulizer.run(self, pool=pool, **kwargs)
 
-        pool.map(self._clean_goal, range(processes), chunksize=1)
+        pool.close()
+        pool.join() # Trigger the finalization functions
 
 
 class Merger():
```

Note: if you want to try this patch in the docker image, you should run `pip3 install --no-cache .` inside the `src/ltlcross_wrapper/` directory after patching it.  The new copy will be installed in `~/.local` and will take precedence over the one in `/usr/local`.

**Comment by adl** [comment]
I haven't been able to reproduce the problem with the above suggested fix.
